#############s######
# MODEL TRAINING
###################

#Dataset generation
window_len : 10     # length of input sequence
stride_len : 1      # stride length

n_times : 2        # faulty dataset size
n_times_orig : 0   # additional clean data

# Ddataset ratio
state_len : 400           # length of trajectory
train_set_ratio : 0.90
dev_set_ratio : 0.05
test_set_ratio : 0.05

# Training
num_epochs : 300        # number of epochs
batchSize : 1024        # batch size
learning_rate : 0.001   # optimizer learning_rate

valid_period : 100   # validation period
valid_size: 100

# SAVE TRAINED MODEL
model_name : 'Model_1'


#############s######
# MODEL SIMULATION
###################
sim_num : 500    # number of traj
sim_len : 399

sim_model_name : 'model_fnn'    # name of model for simulations
sim_normalize: False            # length of input sequence
sim_window_len : 1

sim_fault: True                 # adding the sensor fault
is_plot : True                  # plot the simulation

sim_manual_fault_type : 0       # manually set the fault type 0-pos, 2-vel, 4- wheel
sim_save_result : False
